"""Domain contracts and canonical enums for Candidate Capability Intelligence (CCI)."""

from cci.domain.contracts import (
    AnalysisScore,
    ArtifactAttribution,
    CandidateManifest,
    CapabilityConflict,
    CapabilityEstimate,
    CapabilityUncertainty,
    Claim,
    Dossier,
    EvidenceConfidenceFactors,
    EvidenceInput,
    EvidenceRecord,
    InterviewQuestion,
    NormalizedRequirement,
    OwnershipAssessment,
    ProbePriority,
    RepositoryAssociation,
    RepositoryContribution,
    RoleProfile,
    ScoringConfig,
    SourceReliabilitySnapshot,
)
from cci.domain.enums import (
    AnalysisStage,
    AnalysisStatus,
    ArtifactAttributionState,
    CanonicalRole,
    CapabilityKey,
    ClaimStatus,
    GraphEdgeType,
    GraphNodeType,
    ReliabilityState,
    RequirementPriority,
    RequirementStatus,
    ScanDepth,
    SourceFamily,
    SourceState,
)

__all__ = [
    # Enums
    "AnalysisStage",
    "AnalysisStatus",
    "ArtifactAttributionState",
    "CanonicalRole",
    "CapabilityKey",
    "ClaimStatus",
    "GraphEdgeType",
    "GraphNodeType",
    "ReliabilityState",
    "RequirementPriority",
    "RequirementStatus",
    "ScanDepth",
    "SourceFamily",
    "SourceState",
    # Contracts
    "AnalysisScore",
    "ArtifactAttribution",
    "CandidateManifest",
    "CapabilityConflict",
    "CapabilityEstimate",
    "CapabilityUncertainty",
    "Claim",
    "Dossier",
    "EvidenceConfidenceFactors",
    "EvidenceInput",
    "EvidenceRecord",
    "InterviewQuestion",
    "NormalizedRequirement",
    "OwnershipAssessment",
    "ProbePriority",
    "RepositoryAssociation",
    "RepositoryContribution",
    "RoleProfile",
    "ScoringConfig",
    "SourceReliabilitySnapshot",
]
